"use client";
import {useEffect,useState,type FormEvent} from "react";
import {Save,ShieldCheck,Video,Mail,Landmark,Loader2} from "lucide-react";
import {authenticatedFetch} from "@/lib/authenticated-fetch";
import {siteUrl} from "@/lib/seo";

type Settings=Record<string,string|number|boolean>;
const initial:Settings={stripeWebhookUrl:`${siteUrl}/stripe_webhook`,stripeLiteWebhookUrl:`${siteUrl}/stripe_webhook_lite`,stripeApiVersion:"2022-11-15"};
const secrets=new Set(["stripeSecretKey","stripeWebhookSecret","stripeLiteWebhookSecret","googleAppsScriptMailSecret","dailyApiKey"]);
export default function AdminSettingsPage(){
 const [settings,setSettings]=useState<Settings>(initial),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[testing,setTesting]=useState(false);
 async function load(){const response=await authenticatedFetch("/api/settings");if(!response.ok)throw Error("Les paramètres ne peuvent pas être chargés.");const data=await response.json();const next={...initial,...data};delete next.legalPages;for(const key of secrets)next[key]="";setSettings(next)}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 function update(key:string,value:string){setSettings(s=>({...s,[key]:value}));setMessage("")}
 function field(key:string,label:string,help?:string,type="text"){const secret=secrets.has(key);return <label className="apostolos-setting-field" key={key} htmlFor={`setting-${key}`}><span>{label}</span><input id={`setting-${key}`} className="input" type={secret?"password":type} value={String(settings[key]??"")} onChange={e=>update(key,e.target.value)} autoComplete={secret?"new-password":"off"} placeholder={secret&&settings[`${key}Configured`]?"Déjà configuré — laisser vide pour conserver":""}/>{help&&<small>{help}</small>}{secret&&settings[`${key}Configured`]&&<small className="apostolos-configured">✓ Identifiant enregistré et chiffré</small>}</label>}
 async function submit(event:FormEvent){event.preventDefault();setSaving(true);setMessage("");setError("");try{const payload=Object.fromEntries(Object.entries(settings).filter(([k])=>!k.endsWith("Configured")&&!k.endsWith("Preview")&&!k.startsWith("paypal")&&k!=="paymentProvider"));const response=await authenticatedFetch("/api/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok||!data.verified)throw Error(data.error||"L’enregistrement a échoué.");await load();setMessage("Paramètres enregistrés et vérifiés.")}catch(e){setError(e instanceof Error?e.message:"Le service ne répond pas.")}finally{setSaving(false)}}
 async function verify(){setTesting(true);setError("");setMessage("");try{const response=await authenticatedFetch("/api/payments/stripe/test");const result=await response.json();if(!response.ok||!result.ok)throw Error(result.error||"La vérification a échoué.");setMessage("Connexion Stripe validée. Aucun paiement effectué.")}catch(e){setError(e instanceof Error?e.message:"Le service ne répond pas.")}finally{setTesting(false)}}
 return <section className="section"><div className="container" style={{maxWidth:1140}}><span className="apostolos-label">Configuration</span><h1 className="title">Les services de votre Institut.</h1><p className="subtitle">Paiements, visioconférence et coordonnées, réunis dans un espace de gestion.</p>{loading?<p role="status">Chargement des paramètres…</p>:<form onSubmit={submit} method="post"><fieldset disabled={saving} style={{border:0,padding:0,margin:0}}><div className="apostolos-settings-grid">
 <section className="card apostolos-settings-section"><ShieldCheck/><h2>Paiements Stripe</h2><p className="muted">Le cursus et la bibliothèque utilisent exclusivement Stripe.</p>
 {field("stripePublishableKey","Clé publique Stripe")}{field("stripeSecretKey","Clé secrète Stripe")}{field("stripeWebhookSecret","Secret du webhook Stripe")}{field("stripeWebhookUrl","Adresse du webhook Stripe")}{field("stripeLiteWebhookSecret","Secret du webhook léger")}{field("stripeLiteWebhookUrl","Adresse du webhook léger")}
 <button className="btn btn-outline" type="button" onClick={verify} disabled={testing}>{testing?<Loader2 className="action-spin" size={16}/>:<ShieldCheck size={16}/>}Vérifier la connexion enregistrée</button><p className="muted">Enregistrez vos changements avant de vérifier. Cette action ne crée aucun paiement.</p></section>
 <div className="apostolos-settings-stack"><section className="card apostolos-settings-section"><Video/><h2>Séances en direct</h2>{field("dailyApiKey","Clé API Daily","Les salles privées et les autorisations sont gérées côté serveur.")}</section><section className="card apostolos-settings-section"><Mail/><h2>Messagerie</h2>{field("adminEmail","Email administratif",undefined,"email")}{field("googleAppsScriptMailSecret","Secret de synchronisation","Le déploiement de messagerie doit utiliser le même secret.")}</section><section className="card apostolos-settings-section"><Landmark/><h2>Coordonnées bancaires</h2>{field("beneficiary","Bénéficiaire")}{field("iban","IBAN")}{field("bic","BIC")}{field("rib","RIB affiché aux étudiants")}</section></div>
 </div>{error&&<p className="field-error" role="alert">{error}</p>}{message&&<p className="apostolos-save-result" role="status">{message}</p>}<div className="apostolos-settings-save"><button className="btn btn-primary" disabled={saving}>{saving?<Loader2 className="action-spin" size={18}/>:<Save size={18}/>} {saving?"Enregistrement…":"Enregistrer les paramètres"}</button><span>Les secrets restent chiffrés dans la base.</span></div></fieldset></form>}</div></section>
}
