import {test,expect,mock,beforeEach} from "bun:test";
const id="11111111-1111-4111-8111-111111111111",other="22222222-2222-4222-8222-222222222222";
let denied=false,role="directeur",email:any="a@b.fr",body:any,bodyError:unknown,inputError:unknown,serviceError:unknown,decryptError=false,actor:any,reads:any[]=[],readResults:any[]=[],writes:any[]=[],writeError:any,parsed:any,events:any[]=[],automation:any;
class RequestBodyError extends Error{constructor(public status=413){super("bounded")}}
class ProfileInputError extends Error{constructor(public status=422){super("profile input")}}
class ProfileAdministrationError extends Error{constructor(public status=409){super("assignment")}}
class HomeworkInputError extends Error{constructor(public status=422){super("homework input")}}
const authorization=async()=>denied?{ok:false,response:Response.json({error:"forbidden"},{status:403})}:{ok:true,user:{id,email},profile:{id,email,role,nom:"N",prenom:"P"},context:{}};
mock.module("@/lib/api-auth",()=>({authorizeRequest:authorization,authenticateRequest:authorization}));
mock.module("@/lib/request-body",()=>({RequestBodyError,readJsonBodyWithLimit:async()=>{if(bodyError)throw bodyError;return body},readFormDataBodyWithLimit:async()=>{if(bodyError)throw bodyError;return body}}));
mock.module("@/lib/postgres",()=>({createServerContext:()=>({}),pgRead:async(...args:any[])=>{reads.push(args);return readResults.length?readResults.shift():{data:actor,error:null}},pgInsert:async(...args:any[])=>{writes.push(args);return {data:{id,...args[1]},error:writeError}},pgUpdate:async(...args:any[])=>{writes.push(args);return {data:{id,...args[1]},error:writeError}}}));
const parse=(value:any)=>{if(inputError)throw inputError;return parsed??value};
mock.module("@/lib/profile-input",()=>({ProfileInputError,parseProfileUpdate:parse,parseRegistrationInput:parse}));
mock.module("@/lib/profile-admin",()=>({ProfileAdministrationError,replaceManualCourseEnrollments:async(...args:any[])=>{if(serviceError)throw serviceError;writes.push(args);return [{course_id:other}]}}));
mock.module("@/lib/homework-admin",()=>({HomeworkInputError,parseHomeworkForm:parse,parseHomeworkReview:parse,createHomework:async(...args:any[])=>{if(serviceError)throw serviceError;writes.push(args);return {id}},reviewHomeworkAssignment:async(...args:any[])=>{if(serviceError)throw serviceError;writes.push(args);return {id}}}));
mock.module("@/lib/google-apps-script",()=>({runRegistrationAutomation:async()=>{if(automation instanceof Error||typeof automation==="string")throw automation;return automation}}));
mock.module("@/lib/settings",()=>({secretSettingKeys:new Set(["stripeSecretKey","dailyApiKey"]),protectSettingValue:(key:string,value:any)=>key==="stripeSecretKey"?"encrypted:"+value:value,unprotectSettingValue:(_:string,value:any)=>{if(decryptError)throw new Error("bad ciphertext");return value}}));
mock.module("@/lib/legal",()=>({legalPages:{"mentions-legales":{}}}));
mock.module("@/lib/paypal",()=>({PAYPAL_DEFAULT_AMOUNT_CENTS:100,PAYPAL_WEBHOOK_URL:"https://test/paypal"}));
mock.module("@/lib/stripe",()=>({STRIPE_API_VERSION:"v",STRIPE_LITE_WEBHOOK_URL:"https://test/stripe-lite",STRIPE_WEBHOOK_URL:"https://test/stripe"}));
mock.module("@/lib/security-audit",()=>({recordSecurityEvent:async(e:any)=>{events.push(e)}}));
const homework=await import("@/app/api/homework/route"),review=await import("@/app/api/homework/[id]/route"),users=await import("@/app/api/users/route"),registration=await import("@/app/api/inscription/route"),settings=await import("@/app/api/settings/route");
const req=()=>new Request("https://test.local/api",{method:"POST"}),params={params:Promise.resolve({id})};
beforeEach(()=>{denied=false;role="directeur";email="a@b.fr";body={id};bodyError=inputError=serviceError=undefined;decryptError=false;actor={role};reads=[];readResults=[];writes=[];writeError=null;parsed=undefined;events=[];automation=[]});
test("all administration handlers enforce authentication before touching records",async()=>{denied=true;for(const response of [await homework.GET(req()),await homework.POST(req()),await review.PATCH(req(),params),await users.GET(req()),await users.PATCH(req()),await registration.POST(req()),await settings.GET(req()),await settings.POST(req())])expect(response.status).toBe(403);expect(reads).toHaveLength(0);expect(writes).toHaveLength(0)});
test("homework list binds trainer ownership and reports database failure",async()=>{for(const r of ["directeur","formateur"]){role=r;readResults=[{data:[{id}],error:null}];const response=await homework.GET(req());expect(await response.json()).toEqual([{id}]);expect(reads.at(-1)[1]).toEqual([r!=="formateur",id])}readResults=[{error:{message:"read failed"}}];expect((await homework.GET(req())).status).toBe(400)});
test("admin writes reject oversized and malformed request bodies",async()=>{for(const run of [()=>homework.POST(req()),()=>review.PATCH(req(),params),()=>users.PATCH(req()),()=>registration.POST(req()),()=>settings.POST(req())]){for(const error of [new RequestBodyError(),new Error("bad json")]){bodyError=error;expect((await run()).status).toBe(error instanceof RequestBodyError?413:run.toString().includes("homework.POST")?500:400)}}});
test("homework create validates input, scopes author identity and reports persistence failures",async()=>{inputError=new HomeworkInputError();expect((await homework.POST(req())).status).toBe(422);inputError=undefined;serviceError=new Error("db");expect((await homework.POST(req())).status).toBe(500);serviceError=undefined;const response=await homework.POST(req());expect(response.status).toBe(201);expect(await response.json()).toEqual({ok:true,verified:true,data:{id}});expect(writes[0][1]).toMatchObject({id,role:"directeur"})});
test("homework review returns typed errors and verifies a saved correction",async()=>{for(const error of [new HomeworkInputError(409),new Error("db")]){serviceError=error;expect((await review.PATCH(req(),params)).status).toBe(error instanceof HomeworkInputError?409:500)}serviceError=undefined;expect(await(await review.PATCH(req(),params)).json()).toEqual({ok:true,verified:true,data:{id}});expect(writes[0][0]).toBe(id)});
test("users list returns directory or a database error",async()=>{readResults=[{data:[{id}],error:null},{error:{message:"db"}}];expect(await(await users.GET(req())).json()).toEqual([{id}]);expect((await users.GET(req())).status).toBe(400)});
test("profile edits reject invalid identities, unverifiable actors and cross-user writes",async()=>{for(const input of [{},{id:"invalid"}]){body=input;expect((await users.PATCH(req())).status).toBe(400)}body={id:other};readResults=[{error:{message:"db"}}];expect((await users.PATCH(req())).status).toBe(500);for(const a of [null,{role:"etudiant"}]){actor=a;expect((await users.PATCH(req())).status).toBe(403)}expect(writes).toHaveLength(0)});
test("role and course changes must be separate and profile input errors are bounded",async()=>{body={id,role:"directeur",course_ids:[]};expect((await users.PATCH(req())).status).toBe(400);body={id};for(const error of [new ProfileInputError(),new Error("unknown")]){inputError=error;expect((await users.PATCH(req())).status).toBe(error instanceof ProfileInputError?422:400)}});
test("role edits refuse privilege escalation and self-demotion",async()=>{parsed={};body={id,role:"directeur"};actor={role:"etudiant"};expect((await users.PATCH(req())).status).toBe(403);actor={role:"directeur"};body.role="unknown";expect((await users.PATCH(req())).status).toBe(403);body.role="etudiant";expect((await users.PATCH(req())).status).toBe(409);body.id=other;const response=await users.PATCH(req());expect(response.status).toBe(200);expect(writes[0][1].role).toBe("etudiant");expect(events[0].eventType).toBe("admin.profile.role_changed")});
test("profile update and no-op lookup expose verified results or persistence failures",async()=>{parsed={prenom:"New"};writeError={message:"db"};expect((await users.PATCH(req())).status).toBe(400);writeError=null;expect((await users.PATCH(req())).status).toBe(200);parsed={};readResults=[{data:actor,error:null},{error:{message:"missing"}}];expect((await users.PATCH(req())).status).toBe(404);readResults=[{data:actor,error:null},{data:{id,prenom:"Saved"},error:null}];expect((await(await users.PATCH(req())).json()).profile.prenom).toBe("Saved")});
test("course assignment validates privileges, array shape and service outcome",async()=>{parsed={};body={id,course_ids:[]};actor={role:"etudiant"};expect((await users.PATCH(req())).status).toBe(403);actor={role:"directeur"};body.course_ids="bad";expect((await users.PATCH(req())).status).toBe(400);body.course_ids=[other];for(const error of [new ProfileAdministrationError(),new Error("db")]){serviceError=error;expect((await users.PATCH(req())).status).toBe(error instanceof ProfileAdministrationError?409:500)}serviceError=undefined;expect((await(await users.PATCH(req())).json()).enrollments).toEqual([{course_id:other}]);expect(events.at(-1).eventType).toBe("admin.profile.courses_changed")});
test("registration validates input, binds account identity and does not leak notification errors",async()=>{for(const error of [new ProfileInputError(),new Error("unknown")]){inputError=error;expect((await registration.POST(req())).status).toBe(error instanceof ProfileInputError?422:400)}inputError=undefined;writeError={message:"db"};expect((await registration.POST(req())).status).toBe(400);writeError=null;for(const e of [email,undefined]){email=e;for(const outcome of [[],["private URL"],new Error("private URL"),"private URL"]){automation=outcome;const response=await registration.POST(req());expect(response.status).toBe(200);const json=await response.json();expect(JSON.stringify(json.automationWarnings)).not.toContain("private URL");expect(writes.at(-1)[1]).toMatchObject({id,email:e||""})}}});
test("settings reads fail closed when either table or decryption fails",async()=>{for(const responses of [[{error:{message:"db"}},{data:[]}],[{data:[]},{error:{message:"db"}}]]){readResults=responses;expect((await settings.GET(req())).status).toBe(500)}readResults=[{data:[{key:"stripeSecretKey",value:"private"}]},{data:[]}];decryptError=true;expect((await settings.GET(req())).status).toBe(500)});
test("settings reads never return secrets and normalize bank fields",async()=>{for(const values of [null,[],[{key:"rib",value:"FR-RIB"},{key:"iban",value:"FR-IBAN"},{key:"stripeSecretKey",value:"private"},{key:"dailyApiKey",value:"daily-private"}],[{key:"iban",value:"FR-IBAN"}]]){readResults=[{data:values},{data:values? [{slug:"mentions-legales",contenu:"Legal"}]:null}];const response=await settings.GET(req());expect(response.status).toBe(200);expect(response.headers.get("cache-control")).toBe("private, no-store");const json=await response.json();expect(json.stripeSecretKey).toBe("");expect(json.dailyApiKey).toBe("");expect(JSON.stringify(json)).not.toContain("daily-private");if(values?.length)expect(json.rib).toBe(values.some(v=>v.key==="rib")?"FR-RIB":"FR-IBAN")}});
test("settings updates ignore unknown keys and empty secrets, and persist only known legal pages",async()=>{body={ignored:"bad",stripeSecretKey:" ",legalPages:{"mentions-legales":"Updated","unknown":"No"}};const response=await settings.POST(req());expect(response.status).toBe(200);expect(writes).toHaveLength(1);expect(writes[0][0]).toBe("legal_pages");expect(writes[0][1].slug).toBe("mentions-legales");expect(events[0].eventType).toBe("admin.settings.updated");body={legalPages:"bad"};expect((await settings.POST(req())).status).toBe(200)});
test("settings upsert inserts absent values, updates existing values, and encrypts secrets",async()=>{for(const data of [null,{key:"stripeSecretKey"}]){body={stripeSecretKey:"secret"};readResults=[{data}];const response=await settings.POST(req());expect(response.status).toBe(200);expect(writes.at(-1)[1].value).toBe("encrypted:secret")}body={stripeSecretKey:null};readResults=[{data:null}];expect((await settings.POST(req())).status).toBe(200)});
test("settings report select, update, insert and legal persistence errors without claiming verification",async()=>{for(const scenario of ["select","update","insert","legal"]){body=scenario==="legal"?{legalPages:{"mentions-legales":"Text"}}:{adminEmail:"admin@test.local"};readResults=[scenario==="select"?{error:{message:"db"}}:{data:scenario==="update"?{}:null}];writeError=scenario==="select"?null:{message:"db"};const response=await settings.POST(req());expect(response.status).toBe(500);expect((await response.json()).verified).toBe(false)}});
test("director can configure the video provider without exposing its key",async()=>{body={dailyApiKey:"private-video-key"};readResults=[{data:null}];const response=await settings.POST(req());expect(response.status).toBe(200);expect(writes[0]?.[1]).toMatchObject({key:"dailyApiKey",value:"private-video-key"})});
test("obsolete provider selectors cannot switch payments away from Stripe",async()=>{body={paymentProvider:"paypal"};expect((await settings.POST(req())).status).toBe(200);expect(writes).toHaveLength(0)});
