import {test,expect,mock,beforeEach,afterAll} from "bun:test";
let denied=false,limited=false,limitError=false,originError:unknown,bodyError:unknown,body:any,form:any,readResults:any[]=[],readCalls:any[]=[],writeError:any,writes:any[]=[],storageError:unknown,context:any,matches=true,reference:any,tokenValid=true,queryError=false,fileError=false,events:any[]=[];
const id="11111111-1111-4111-8111-111111111111",image=Buffer.from("RIFF0000WEBP0000");
class RequestBodyError extends Error{constructor(public status=413){super("body")}}
class RequestSecurityError extends Error{constructor(public status=403){super("origin")}}
const auth=async()=>denied?{ok:false,response:Response.json({error:"denied"},{status:401})}:{ok:true,user:{id},context:{}};
mock.module("@/lib/api-auth",()=>({authenticateRequest:auth,authorizeRequest:auth}));
mock.module("@/lib/request-body",()=>({RequestBodyError,readJsonBodyWithLimit:async()=>{if(bodyError)throw bodyError;return body},readFormDataBodyWithLimit:async()=>{if(bodyError)throw bodyError;return form}}));
mock.module("@/lib/request-security",()=>({RequestSecurityError,assertSameOrigin:()=>{if(originError)throw originError},getTrustedClientIp:()=>"127.0.0.1"}));
mock.module("@/lib/rate-limit",()=>({checkRateLimit:async()=>{if(limitError)throw new Error("db");return {allowed:!limited,retryAfterSeconds:30}}}));
mock.module("@/lib/postgres",()=>({createServerContext:()=>context,pgRead:async(...args:any[])=>{readCalls.push(args);return readResults.shift()??{data:null,error:null}},pgUpdate:async(...args:any[])=>{writes.push(args);return {data:{id,...args[1]},error:writeError}}}));
mock.module("@/lib/db",()=>({query:async(...args:any[])=>{writes.push(args);if(queryError)throw new Error("db");return []}}));
mock.module("@/lib/avatar-storage",()=>({readAvatarImage:async()=>{if(storageError)throw storageError;return image},normalizeAvatarImage:async()=>{if(storageError)throw storageError;return image},storeAvatarImage:async(...args:any[])=>{writes.push(args)}}));
mock.module("@/lib/document-verification",()=>({matchesDeclaredRecipient:()=>matches,normalizeDocumentReference:()=>reference}));
mock.module("@/lib/learning-documents",()=>({learningDocumentFilename:()=>"certificate.pdf"}));
mock.module("@/lib/learning-document-pdf",()=>({renderLearningDocumentPdf:async()=>Buffer.from("%PDF-1.7 test")}));
mock.module("@/lib/email-optout",()=>({verifyEmailOptoutToken:()=>tokenValid}));
mock.module("@/lib/security-audit",()=>({recordSecurityEvent:async(e:any)=>{events.push(e)}}));
mock.module("node:fs/promises",()=>({readFile:async()=>{if(fileError)throw new Error("missing file");return "authorized file content"}}));
const avatar=await import("@/app/api/avatars/[id]/route"),upload=await import("@/app/api/profile/avatar/route"),document=await import("@/app/api/documents/[id]/route"),verify=await import("@/app/api/documents/verify/route"),optout=await import("@/app/api/emails/desinscription/route"),report=await import("@/app/api/download/rapport/route"),script=await import("@/app/api/download/google-apps-script/route"),share=await import("@/app/api/download/apps-script-partage/route");
const req=(suffix="")=>new Request("https://test.local/api"+suffix),params=(value=id)=>({params:Promise.resolve({id:value})}),row=(data:any,error:any=null)=>({data,error});
const originalStorage=process.env.AVATAR_STORAGE_DIR;afterAll(()=>{if(originalStorage===undefined)delete process.env.AVATAR_STORAGE_DIR;else process.env.AVATAR_STORAGE_DIR=originalStorage});
function file(bytes:Uint8Array|string=image,type="image/webp"){form=new FormData();form.set("file",new File([typeof bytes==="string"?bytes:Uint8Array.from(bytes)],"avatar",{type}))}
beforeEach(()=>{denied=false;limited=false;limitError=false;originError=bodyError=storageError=undefined;body={reference:"REF",recipient:"Nom Prénom"};file();readResults=[];readCalls=[];writeError=null;writes=[];context={};matches=true;reference="REF";tokenValid=true;queryError=fileError=false;events=[];process.env.AVATAR_STORAGE_DIR="test-storage"});
test("avatars validate storage and identity, cache by content hash, and return not-found on read failure",async()=>{delete process.env.AVATAR_STORAGE_DIR;expect((await avatar.GET(req(),params())).status).toBe(404);process.env.AVATAR_STORAGE_DIR="test-storage";expect((await avatar.GET(req(),params("bad"))).status).toBe(404);const response=await avatar.GET(req(),params());expect(response.status).toBe(200);expect(response.headers.get("content-type")).toBe("image/webp");expect(response.headers.get("x-content-type-options")).toBe("nosniff");expect(await response.arrayBuffer()).toEqual(image.buffer.slice(image.byteOffset,image.byteOffset+image.byteLength));const cached=await avatar.GET(new Request("https://test.local",{headers:{"if-none-match":response.headers.get("etag")!}}),params());expect(cached.status).toBe(304);storageError=new Error("missing");expect((await avatar.GET(req(),params())).status).toBe(404)});
test("avatar uploads require authentication, rate limits and a bounded multipart body",async()=>{denied=true;expect((await upload.POST(req())).status).toBe(401);denied=false;limited=true;expect((await upload.POST(req())).status).toBe(429);limited=false;for(const error of [new RequestBodyError(),new Error("bad")]){bodyError=error;expect((await upload.POST(req())).status).toBe(error instanceof RequestBodyError?413:400)}expect(writes).toHaveLength(0)});
test("avatar uploads refuse empty, oversized, unsupported and spoofed images",async()=>{for(const invalid of [undefined,new FormData()]){form=invalid;expect((await upload.POST(req())).status).toBe(400)}for(const [bytes,type] of [["short","image/png"],[new Uint8Array(3*1024*1024+1),"image/png"],[image,"text/plain"],[new Uint8Array(16),"image/jpeg"],[new Uint8Array([255,0,...new Uint8Array(14)]),"image/jpeg"],[new Uint8Array([255,216,0,...new Uint8Array(13)]),"image/jpeg"],[new Uint8Array(16),"image/png"],["XXXX0000WEBP0000","image/webp"],["RIFF0000XXXX0000","image/webp"]] as const){file(bytes,type);expect((await upload.POST(req())).status).toBe(400)}expect(writes).toHaveLength(0)});
test("avatar uploads normalize supported formats and only update the authenticated profile",async()=>{for(const [bytes,type] of [[new Uint8Array([255,216,255,...new Uint8Array(13)]),"image/jpeg"],[new Uint8Array([137,80,78,71,13,10,26,10,...new Uint8Array(8)]),"image/png"],[image,"image/webp"]] as const){file(bytes,type);const response=await upload.POST(req());expect(response.status).toBe(200);expect((await response.json()).verified).toBe(true);expect(writes.at(-1)[3]).toEqual([id]);expect(writes.at(-1)[1].avatar_url).toStartWith(`/api/avatars/${id}?v=`)}});
test("avatar upload reports absent storage, decode errors and profile persistence errors",async()=>{delete process.env.AVATAR_STORAGE_DIR;expect((await upload.POST(req())).status).toBe(503);process.env.AVATAR_STORAGE_DIR="test-storage";for(const error of [new Error("private decoder detail"),"private detail"]){storageError=error;const response=await upload.POST(req());expect(response.status).toBe(502);expect(JSON.stringify(await response.json())).not.toContain("private")}storageError=undefined;writeError={message:"db"};expect((await upload.POST(req())).status).toBe(502)});
test("document download fails closed on authentication, identity and profile lookup",async()=>{denied=true;expect((await document.GET(req(),params())).status).toBe(401);denied=false;expect((await document.GET(req(),params("bad"))).status).toBe(404);for(const data of [row(null,{message:"db"}),row(null)]){readResults=[data];expect((await document.GET(req(),params())).status).toBe(503)}readResults=[row({role:"etudiant"}),row(null,{message:"db"})];expect((await document.GET(req(),params())).status).toBe(503);readResults=[row({role:"etudiant"}),row(null)];expect((await document.GET(req(),params())).status).toBe(404)});
test("document download scopes student ownership and streams a private PDF",async()=>{for(const role of ["etudiant","directeur"]){readResults=[row({role}),row({id})];const response=await document.GET(req(),params());expect(response.status).toBe(200);expect(readCalls.at(-1)[1]).toEqual([id,role==="directeur",id]);expect(response.headers.get("content-type")).toBe("application/pdf");expect(response.headers.get("cache-control")).toBe("private, no-store");expect(await response.text()).toStartWith("%PDF")}});
test("document verification validates origin, rate, body and bounded recipient",async()=>{for(const error of [new RequestSecurityError(),"origin"]){originError=error;expect((await verify.POST(req())).status).toBe(403)}originError=undefined;limited=true;expect((await verify.POST(req())).status).toBe(429);limited=false;for(const error of [new RequestBodyError(),new Error("bad")]){bodyError=error;expect((await verify.POST(req())).status).toBe(error instanceof RequestBodyError?413:400)}bodyError=undefined;reference=null;expect(await(await verify.POST(req())).json()).toEqual({valid:false});reference="REF";for(const recipient of [undefined,"x".repeat(241)]){body.recipient=recipient;expect(await(await verify.POST(req())).json()).toEqual({valid:false})}});
test("document verification reveals only a matching named document's public facts",async()=>{context=null;expect((await verify.POST(req())).status).toBe(503);context={};readResults=[row(null,{message:"db"})];expect((await verify.POST(req())).status).toBe(503);readResults=[row(null)];expect(await(await verify.POST(req())).json()).toEqual({valid:false});matches=false;readResults=[row({recipient_name:"Other"})];expect(await(await verify.POST(req())).json()).toEqual({valid:false});matches=true;for(const titles of [{},{course_title:"Course",module_title:"Module"}]){readResults=[row({document_number:"REF",recipient_name:"PRIVATE NAME",document_kind:"module",issued_at:"date",...titles})];const response=await verify.POST(req());expect(response.status).toBe(200);const data=await response.json();expect(data.valid).toBe(true);expect(data.document.courseTitle).toBe(titles.course_title||null);expect(JSON.stringify(data)).not.toContain("PRIVATE NAME")}});
test("unsubscribe validates signed links and fails closed on unavailable limits or database",async()=>{for(const suffix of ["","?profil=bad&jeton=x",`?profil=${id}`])expect((await optout.GET(req(suffix))).status).toBe(400);const request=req(`?profil=${id}&jeton=valid`);limited=true;expect((await optout.GET(request)).status).toBe(429);limited=false;limitError=true;expect((await optout.GET(request)).status).toBe(503);limitError=false;tokenValid=false;expect((await optout.GET(request)).status).toBe(400);tokenValid=true;queryError=true;expect((await optout.GET(request)).status).toBe(503);queryError=false;const response=await optout.GET(request);expect(response.status).toBe(200);expect(response.headers.get("cache-control")).toBe("private, no-store");expect(await response.text()).toContain("Désinscription confirmée");expect(writes.at(-1)[1]).toEqual([id])});
test("administrative downloads require director authorization and audit script access",async()=>{for(const run of [()=>report.GET(req()),()=>script.POST(req()),()=>share.GET(req())]){denied=true;expect((await run()).status).toBe(401);denied=false;fileError=true;expect((await run()).status).toBe(503);fileError=false;const response=await run();expect(response.status).toBe(200);expect(response.headers.get("cache-control")).toBe("private, no-store");expect(response.headers.get("x-content-type-options")).toBe("nosniff");expect(await response.text()).toBe("authorized file content")}expect(events).toHaveLength(2);expect(events.every(e=>e.actorUserId===id&&e.eventType==="admin.google_script.downloaded")).toBe(true)});
