import {test,expect,mock,beforeEach,afterAll} from "bun:test";
let denied=false,originError:unknown,bodyError:unknown,inputError:unknown,body:any,limited=false,limitError=false,limits:any,config:any,serviceError:unknown,order:any,reversed=false,expected=true,summary:any,settlement:any,active=true,writeError:any,storedStatus:any,writes:any[]=[],events:any[]=[],fetchResponse:any,fetchCalls:any[]=[],mailCalls=0,contactInput:any;
class RequestBodyError extends Error{constructor(public status=413){super("body")}}
class RequestSecurityError extends Error{constructor(public status=403){super("origin")}}
class ContactInputError extends Error{constructor(public status=422){super("contact")}}
const id="11111111-1111-4111-8111-111111111111",okLimit={allowed:true,retryAfterSeconds:0},noLimit={allowed:false,retryAfterSeconds:55};
const auth=async()=>denied?{ok:false,response:Response.json({error:"denied"},{status:403})}:{ok:true,user:{id},context:{}};
mock.module("@/lib/api-auth",()=>({authenticateRequest:auth,authorizeRequest:auth}));
mock.module("@/lib/request-security",()=>({RequestSecurityError,assertSameOrigin:()=>{if(originError)throw originError},getTrustedClientIp:()=>"127.0.0.1"}));
mock.module("@/lib/request-body",()=>({RequestBodyError,readJsonBodyWithLimit:async()=>{if(bodyError)throw bodyError;return body}}));
mock.module("@/lib/rate-limit",()=>({checkRateLimit:async()=>{if(limitError)throw new Error("db");return limited?noLimit:okLimit},checkRateLimitHierarchy:async()=>limits}));
mock.module("@/lib/settings",()=>({getSystemSettings:async()=>{if(serviceError)throw serviceError;return {}}}));
mock.module("@/lib/stripe",()=>({STRIPE_API_VERSION:"default-version",getStripeConfig:()=>config,retrieveStripeObject:async()=>({}),extractStripeCheckoutSessionSummary:()=>summary,isExpectedStripeSession:()=>expected}));
mock.module("@/lib/paypal",()=>({getPayPalConfig:()=>config,generatePayPalAccessToken:async()=>{if(serviceError)throw serviceError;return "private"}}));
mock.module("@/lib/stripe-settlement",()=>({findStripeOrder:async(args:any)=>{writes.push(args);if(serviceError)throw serviceError;return order},normalizeStripeProductType:()=>"annual_pass",isReversedStripeOrderStatus:()=>reversed,stripeReconciliationStatus:()=>"unpaid",settlePaidStripeSession:async(args:any)=>{writes.push(args);return settlement},hasActiveStripeEntitlement:async()=>active}));
mock.module("@/lib/postgres",()=>({pgUpdate:async(...args:any[])=>{writes.push(args);return {data:{id,statut_inscription:storedStatus??args[1].statut_inscription},error:writeError}}}));
mock.module("@/lib/security-audit",()=>({hashAuditSubject:()=>"hash",recordSecurityEvent:async(e:any)=>{events.push(e)}}));
mock.module("@/lib/contact",()=>({ContactInputError,parseContactInput:()=>{if(inputError)throw inputError;return contactInput}}));
mock.module("@/lib/google-apps-script",()=>({sendContactMessage:async()=>{mailCalls++;if(serviceError)throw serviceError}}));
const originalFetch=globalThis.fetch;globalThis.fetch=Object.assign(async(...args:any[])=>{fetchCalls.push(args);return fetchResponse},{preconnect:originalFetch.preconnect});afterAll(()=>{globalThis.fetch=originalFetch});
const stripe=await import("@/app/api/payments/stripe/test/route"),paypal=await import("@/app/api/payments/paypal/test/route"),reconcile=await import("@/app/api/payments/stripe/reconcile/route"),payment=await import("@/app/api/payments/[id]/route"),contact=await import("@/app/api/contact/route");
const req=()=>new Request("https://test.local/api/payments",{method:"POST"}),params=(value=id)=>({params:Promise.resolve({id:value})});
beforeEach(()=>{denied=false;originError=bodyError=inputError=serviceError=undefined;body={sessionId:"cs_valid_session_123"};limited=false;limitError=false;limits={broad:okLimit,specific:okLimit};config={secretKey:"server-key",apiVersion:"version",webhookSecret:"webhook",liteWebhookSecret:"lite",clientId:"client",clientSecret:"private",appName:"Apostolos",environment:"sandbox",webhookId:"webhook",webhookUrl:"https://test/webhook"};order={id,product_type:"annual_pass",status:"created"};reversed=false;expected=true;summary={paymentStatus:"paid"};settlement={ok:true,order,productType:"annual_pass"};active=true;writeError=null;storedStatus=undefined;writes=[];events=[];fetchResponse={ok:true,json:async()=>({})};fetchCalls=[];mailCalls=0;contactInput={email:"a@b.fr",website:""}});
test("payment administration and reconciliation require authentication",async()=>{denied=true;for(const response of [await stripe.GET(req()),await paypal.GET(req()),await reconcile.POST(req()),await payment.PATCH(req(),params())])expect(response.status).toBe(403);expect(fetchCalls).toHaveLength(0)});
test("provider connection tests validate required credentials and do not return private keys",async()=>{config.secretKey="";expect((await stripe.GET(req())).status).toBe(400);config.clientId="";expect((await paypal.GET(req())).status).toBe(400);config.clientId="id";config.clientSecret="";expect((await paypal.GET(req())).status).toBe(400);config.clientSecret="private";const response=await paypal.GET(req());expect(response.status).toBe(200);expect(await response.json()).toMatchObject({environment:"sandbox",webhookConfigured:true});config.secretKey="server-key";for(const version of ["version",undefined]){config.apiVersion=version;const result=await stripe.GET(req());expect(result.status).toBe(200);expect((await result.json()).apiVersion).toBe(version||"default-version");expect(fetchCalls.at(-1)[1].headers.Authorization).toBe("Bearer server-key");expect(JSON.stringify(await(await paypal.GET(req())).json())).not.toContain("private")}});
test("provider tests handle provider rejection, non-JSON output and thrown failures",async()=>{for(const data of [{error:{message:"rejected"}},null]){fetchResponse={ok:false,json:async()=>data};expect((await stripe.GET(req())).status).toBe(400)}fetchResponse={ok:false,json:async()=>{throw new Error("bad JSON")}};expect((await stripe.GET(req())).status).toBe(400);for(const error of [new Error("offline"),"offline"]){serviceError=error;expect((await stripe.GET(req())).status).toBe(400);expect((await paypal.GET(req())).status).toBe(400)}});
test("reconciliation rejects foreign origins, unavailable limits and malformed payloads",async()=>{for(const error of [new RequestSecurityError(),"origin"]){originError=error;expect((await reconcile.POST(req())).status).toBe(403)}originError=undefined;limitError=true;expect((await reconcile.POST(req())).status).toBe(503);limitError=false;limited=true;expect((await reconcile.POST(req())).status).toBe(429);limited=false;for(const error of [new RequestBodyError(),new Error("bad JSON")]){bodyError=error;expect((await reconcile.POST(req())).status).toBe(error instanceof RequestBodyError?413:400)}bodyError=undefined;for(const invalid of [null,[],"text",{}, {sessionId:42},{sessionId:"bad"}]){body=invalid;expect((await reconcile.POST(req())).status).toBe(400)}expect(writes).toHaveLength(0)});
test("reconciliation scopes the order to its owner and refuses mismatched provider facts",async()=>{order=null;expect((await reconcile.POST(req())).status).toBe(404);expect(writes[0]).toMatchObject({sessionId:"cs_valid_session_123",userId:id});order={status:"refunded"};reversed=true;expect((await(await reconcile.POST(req())).json()).status).toBe("unpaid");reversed=false;expected=false;expect((await reconcile.POST(req())).status).toBe(409);expected=true;summary.paymentStatus="unpaid";expect((await(await reconcile.POST(req())).json()).status).toBe("unpaid")});
test("reconciliation only reports active after verified settlement and entitlement",async()=>{settlement={ok:false,reason:"amount_mismatch"};expect((await reconcile.POST(req())).status).toBe(409);settlement={ok:true,order,productType:"annual_pass"};for(const entitlement of [true,false]){active=entitlement;const response=await reconcile.POST(req());expect(response.status).toBe(200);expect(response.headers.get("cache-control")).toBe("private, no-store");expect((await response.json()).status).toBe(entitlement?"active":"processing")}for(const error of [new Error("entitlement_lookup_failed"),new Error("private provider failure"),"private"]){serviceError=error;const response=await reconcile.POST(req());expect(response.status).toBe(503);expect(await response.json()).toEqual({ok:false,status:"processing"})}});
test("manual payment decisions validate identity, bounded body and allowed statuses",async()=>{expect((await payment.PATCH(req(),params("bad"))).status).toBe(404);for(const error of [new RequestBodyError(),new Error("bad")]){bodyError=error;expect((await payment.PATCH(req(),params())).status).toBe(error instanceof RequestBodyError?413:400)}bodyError=undefined;body={statut:"bad"};expect((await payment.PATCH(req(),params())).status).toBe(400)});
test("manual decisions verify the stored state and audit validation, revocation and pending",async()=>{body={};writeError={message:"db"};expect((await payment.PATCH(req(),params())).status).toBe(500);writeError=null;storedStatus="wrong";expect((await payment.PATCH(req(),params())).status).toBe(409);storedStatus=undefined;for(const [status,event] of [["validee","validated"],["refusee","revoked"],["en_attente","status_changed"]]){body={statut:status};const response=await payment.PATCH(req(),params());expect(response.status).toBe(200);expect((await response.json()).verified).toBe(true);expect(events.at(-1).eventType).toBe("payment.manual."+event);expect(writes.at(-1)[3]).toEqual([id])}});
test("contact rejects cross-origin, malformed, oversized and invalid messages",async()=>{for(const error of [new RequestSecurityError(),"origin"]){originError=error;expect((await contact.POST(req())).status).toBe(403)}originError=undefined;for(const error of [new RequestBodyError(),new ContactInputError(),new Error("bad")]){inputError=error;expect((await contact.POST(req())).status).toBe(error instanceof RequestBodyError?413:error instanceof ContactInputError?422:400)}expect(mailCalls).toBe(0)});
test("contact limits spam, silently accepts honeypots, and accurately reports delivery",async()=>{for(const value of [{broad:noLimit,specific:okLimit},{broad:okLimit,specific:noLimit},{broad:noLimit,specific:undefined}]){limits=value;expect((await contact.POST(req())).status).toBe(429)}limits={broad:okLimit,specific:okLimit};contactInput.website="spam";expect((await contact.POST(req())).status).toBe(202);expect(mailCalls).toBe(0);contactInput.website="";const response=await contact.POST(req());expect(response.status).toBe(202);expect(response.headers.get("cache-control")).toBe("no-store");expect(mailCalls).toBe(1);serviceError=new Error("offline");expect((await contact.POST(req())).status).toBe(503)});
