import Link from "next/link";
import {ArrowUpRight,BookOpen} from "lucide-react";
import {getCourses} from "@/lib/server-data";
import {getOptionalPageProfile} from "@/lib/page-auth";
import {BuyCourseButton} from "@/components/BuyCourseButton";
import {Suspense} from "react";
export const dynamic="force-dynamic";
export const metadata={title:"Les cours — Un parcours pour comprendre",description:"Découvrez les cours et modules de l’Institut Apostolos Saint Irénée."};
export default async function FormationsPage(){
 const [courses,profile]=await Promise.all([getCourses(),getOptionalPageProfile()]);
 return <div className="apostolos-wrap"><header className="apostolos-catalog-head"><span className="apostolos-label">LE PROGRAMME APOSTOLOS</span><h1>Le goût de comprendre.<br/><em>La joie d’apprendre.</em></h1><p>Des fondements aux grandes questions contemporaines : choisissez votre point de départ et avancez, module après module.</p></header><div className="apostolos-catalog-layout"><aside className="apostolos-catalog-aside"><div><span className="apostolos-label">VOTRE PARCOURS</span><h3>{courses.length} cours à explorer</h3><p>{courses.reduce((n,c)=>n+Number(c.nb_modules||0),0)} modules de formation</p></div><p>Votre espace personnel réunit les cours accessibles, vos lectures et votre progression.</p>{profile?<Link href="/espace-etudiant" className="apostolos-text-link">Retrouver mon espace <ArrowUpRight size={16}/></Link>:<Suspense fallback={<Link href="/auth/signup">Créer mon compte</Link>}><BuyCourseButton className="apostolos-cta" label="Rejoindre le parcours"/></Suspense>}</aside><div className="apostolos-catalog-list">{courses.length?courses.map((course,i)=><article className="apostolos-catalog-row" key={course.id} id={`cours-${course.id}`}><span className="apostolos-number">{String(i+1).padStart(2,"0")}</span><div><span className="apostolos-label">{course.nb_modules} MODULES · {course.niveau==="avance"?"APPROFONDISSEMENT":"PARCOURS D’ÉTUDE"}</span><h2>{course.titre}</h2><p>{course.description}</p>{course.objectifs.length>0&&<details><summary>Ce que vous allez explorer</summary><ul>{course.objectifs.map((o,index)=><li key={index}>{o}</li>)}</ul></details>}<Link className="apostolos-text-link" href={profile?`/cours/${encodeURIComponent(course.slug)}`:`/auth/login?next=${encodeURIComponent(`/cours/${course.slug}`)}`}><BookOpen size={16}/>{profile?"Ouvrir le cours":"Se connecter pour étudier"}<ArrowUpRight size={16}/></Link></div></article>):<div className="apostolos-empty">Le catalogue est momentanément indisponible. Réessayez dans quelques instants.</div>}</div></div></div>;
}
