server_tokens off;

limit_req_zone $binary_remote_addr zone=irenee_general:10m rate=20r/s;
limit_req_zone $binary_remote_addr zone=irenee_auth:10m rate=30r/m;
limit_conn_zone $binary_remote_addr zone=irenee_connections:10m;
limit_req_status 429;
limit_conn_status 429;
