import Image from "next/image";
import Link from "next/link";
import {ArrowUpRight,ArrowRight,BookOpen,Layers,Compass} from "lucide-react";
import {getCourses} from "@/lib/server-data";
export const dynamic="force-dynamic";
export const metadata={title:{absolute:"Institut Apostolos Saint Irénée — Comprendre pour transmettre"}};
export default async function Home(){
 const courses=await getCourses();const moduleCount=courses.reduce((n,c)=>n+Number(c.nb_modules||0),0);
 return <div className="apostolos-home">
 <section className="apostolos-hero apostolos-wrap"><div className="apostolos-hero-copy"><span className="apostolos-label"><span className="apostolos-dot"/> UNE ÉCOLE DE LA FOI ET DE LA RAISON</span><h1>Une foi éclairée.<br/>Une parole<br/><em>qui transmet.</em></h1><p>Prendre le temps de comprendre. Remonter aux sources. Apprendre à rendre compte de la foi catholique avec intelligence et charité.</p><div className="apostolos-actions"><Link href="/formations" className="apostolos-cta">Découvrir les cours <ArrowUpRight size={19}/></Link><Link href="/a-propos" className="apostolos-text-link">L’esprit Apostolos <ArrowRight size={17}/></Link></div><div className="apostolos-hero-proof"><span><strong>{courses.length}</strong> cours pour approfondir</span><span><strong>{moduleCount}</strong> modules à explorer</span><span>À votre rythme,<br/><strong>où que vous soyez.</strong></span></div></div><div className="apostolos-hero-image"><Image src="/images/apostolos/cloitre.png" alt="Un livre ouvert dans la lumière d’un cloître, au bord d’un jardin d’oliviers" fill priority sizes="(max-width: 800px) 100vw, 50vw"/><div className="apostolos-image-note"><span>ÉTUDIER · COMPRENDRE · TRANSMETTRE</span><strong>Le savoir prend racine<br/>dans l’attention.</strong></div></div></section>
 <section className="apostolos-intro"><div className="apostolos-wrap apostolos-intro-grid"><span className="apostolos-label">NOTRE CONVICTION</span><h2>La foi ne demande pas<br/>de renoncer à <em>comprendre.</em></h2><p>L’Écriture, la tradition chrétienne, la philosophie et l’histoire se rencontrent dans un parcours structuré. Chaque cours ouvre une question ; chaque module donne des repères pour la travailler.</p></div></section>
 <section className="apostolos-section apostolos-wrap"><div className="apostolos-section-head"><div><span className="apostolos-label">LE PROGRAMME</span><h2>Des fondations solides.<br/>Des horizons ouverts.</h2></div><Link href="/formations" className="apostolos-text-link">Voir tous les cours <ArrowUpRight size={18}/></Link></div><div className="apostolos-course-grid">{courses.slice(0,3).map((course,i)=><Link href={`/formations#cours-${course.id}`} key={course.id} className="apostolos-course-tile"><div className={`apostolos-course-art art-${i}`}><span>APOSTOLOS / ÉTUDES</span>{i===0?<BookOpen size={62} strokeWidth={.8}/>:i===1?<Compass size={62} strokeWidth={.8}/>:<Layers size={62} strokeWidth={.8}/>}<b>{String(i+1).padStart(2,"0")}</b></div><div className="apostolos-course-body"><span className="apostolos-label">{course.nb_modules} MODULES · À VOTRE RYTHME</span><h3>{course.titre}</h3><p>{course.description}</p><span className="apostolos-text-link">Explorer ce cours <ArrowUpRight size={18}/></span></div></Link>)}</div></section>
 <section className="apostolos-method apostolos-wrap"><div className="apostolos-method-image"><Image src="/images/apostolos/etude.png" alt="Livres d’étude et branche d’olivier sur une table de lecture" fill sizes="(max-width:800px) 100vw, 45vw"/></div><div className="apostolos-method-copy"><span className="apostolos-label">UNE MÉTHODE, UN CHEMIN</span><h2>Apprendre vraiment.<br/><em>Un pas après l’autre.</em></h2>{[["01","Entrer dans une question","Des cours organisés pour poser les fondements avant les approfondissements."],["02","Prendre le temps d’étudier","Des modules de lecture et des ressources à retrouver dans votre espace."],["03","Faire vivre ce que l’on apprend","Une progression personnelle pour relier le savoir à la réflexion et au dialogue."]].map(([n,title,text])=><div className="apostolos-step" key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}<Link href="/formations" className="apostolos-text-link">Trouver mon point de départ <ArrowUpRight size={18}/></Link></div></section>
 <section className="apostolos-invitation"><div className="apostolos-wrap"><span className="apostolos-label">INSTITUT APOSTOLOS SAINT IRÉNÉE</span><h2>Et si votre prochaine question<br/>devenait un <em>chemin d’étude ?</em></h2><Link href="/formations" className="apostolos-cta">Entrer dans le programme <ArrowUpRight size={18}/></Link></div></section>
 </div>;
}
