import Image from "next/image";
import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowLeft,ArrowUpRight} from "lucide-react";
import {blogArticles,getBlogArticle,getRelatedArticles,formatArticleDate} from "@/lib/blog";
import {siteName,siteUrl} from "@/lib/seo";
import {JsonLd} from "@/components/JsonLd";
import type { Metadata } from "next";
export function generateStaticParams(){return blogArticles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const a=getBlogArticle((await params).slug);if(!a)return{};return{title:a.title,description:a.description,alternates:{canonical:`/blog/${a.slug}`},openGraph:{type:"article",url:`/blog/${a.slug}`,title:a.title,description:a.description,siteName,images:[{url:a.image,alt:a.imageAlt}],publishedTime:a.date,section:a.category,tags:a.tags},twitter:{card:"summary_large_image",title:a.title,description:a.description,images:[a.image]}}}
export default async function Article({params}:{params:Promise<{slug:string}>}){
 const article=getBlogArticle((await params).slug);if(!article)notFound();const related=getRelatedArticles(article);
 const articleUrl=`${siteUrl}/blog/${article.slug}`;
 return <article className="apostolos-wrap apostolos-article"><JsonLd data={{"@context":"https://schema.org","@type":"BlogPosting","@id":articleUrl,"url":articleUrl,mainEntityOfPage:{"@type":"WebPage","@id":articleUrl},headline:article.title,description:article.description,datePublished:article.date,image:`${siteUrl}${article.image}`,articleSection:article.category,keywords:article.tags,author:{"@type":"Organization","name":siteName,"url":siteUrl},publisher:{"@type":"Organization","name":siteName,"url":siteUrl}}}/><header className="apostolos-article-header"><Link href="/blog" className="apostolos-text-link"><ArrowLeft size={16}/>Le journal</Link><span className="apostolos-label">{article.category} · {formatArticleDate(article.date)} · {article.readingMinutes} MIN</span><h1>{article.title}</h1><p>{article.description}</p></header><div className="apostolos-article-image"><Image src={article.image} alt={article.imageAlt} fill priority sizes="(max-width:800px) 100vw, 80vw"/></div><div className="apostolos-article-layout"><aside><span className="apostolos-label">DANS CET ARTICLE</span>{article.sections.map((s,i)=><a key={s.heading} href={`#partie-${i+1}`}>{String(i+1).padStart(2,"0")} — {s.heading}</a>)}</aside><div className="apostolos-article-body">{article.intro.map((paragraph,index)=><p key={`intro-${index}`} className={index===0?"apostolos-article-lead":undefined}>{paragraph}</p>)}{article.sections.map((s,i)=><section key={s.heading} id={`partie-${i+1}`}><h2>{s.heading}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}{article.takeaways.length>0&&<section className="apostolos-article-takeaways"><h2>À retenir</h2><ul>{article.takeaways.map(item=><li key={item}>{item}</li>)}</ul></section>}{article.sources.length>0&&<section className="apostolos-article-sources"><h2>Pour poursuivre</h2><ul>{article.sources.map(source=><li key={source.id}>{source.url.startsWith("/")?<Link href={source.url}>{source.label}</Link>:<a href={source.url} target="_blank" rel="noreferrer">{source.label}</a>}</li>)}</ul></section>}<div className="apostolos-article-next"><span className="apostolos-label">POURSUIVRE L’ÉTUDE</span><h2>Un texte ouvre une question.<br/>Un cours permet de la travailler.</h2><Link href="/formations" className="apostolos-cta">Explorer le programme <ArrowUpRight size={17}/></Link></div></div></div><section className="apostolos-section"><div className="apostolos-section-head"><h2>Prolonger la réflexion</h2></div><div className="apostolos-journal-grid">{related.map(a=><Link key={a.slug} href={`/blog/${a.slug}`} className="apostolos-journal-card"><span className="apostolos-label">{a.category}</span><h2>{a.title}</h2><span className="apostolos-text-link">Lire l’article <ArrowUpRight size={16}/></span></Link>)}</div></section></article>
}
